#
# Pull Release Pipeline
#
# This pipeline gets run for all PRs into the master branch
# ignoring all markdown (*.md) files. The artifacts produced
# will all have the '-beta' version suffix.
#
name: '1.9.$(date:yyMM).$(date:dd)$(rev:rrr)-ramsey-beta'

resources:
- repo: self

trigger: none
pr:
  branches:
    include:
    - main-ramsey
  paths:
    exclude:
    - '**/*.md'

jobs:
- template: build-template.yml
