jobs:
- job: 'BuildAndPublishJob'

  pool:
    vmImage: 'windows-latest'

  workspace:
    clean: all

  steps:

  # Restore NuGet Packages.
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: 'MediaManager.sln'
      verbosityRestore: 'Normal'

  # Build the solution.
  - task: MSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: 'MediaManager.sln'
      msbuildArguments: '/p:Configuration=Release /p:OfficialBuildNumber=$(Build.BuildNumber) /p:NoWarn=NU1605'

  # Run the unit tests.
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: 'MediaManager.UnitTest/MediaManager.UnitTest.csproj'
      arguments: '--configuration Release --no-build'

  # Build the NuGet package.
  - task: DotNetCoreCLI@2
    displayName: 'Build NuGet package'
    inputs:
      command: pack
      nobuild: true
      packagesToPack: 'MediaManager*/**/*.csproj'
      configuration: Release
      buildProperties: 'OfficialBuildNumber=$(Build.BuildNumber)'
      verbosityPack: Normal
      packDirectory: '$(Build.ArtifactStagingDirectory)'

  # Publish the NuGet package to the Azure Pipeline.
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nuget'
      publishLocation: 'Container'
